version: "3.9"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./forum-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: "npm run dev"
    stdin_open: true
