version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./forum-app:/app/forum-app
      - /app/forum-app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
